# **ET720 Calculo de fluxo de potência**

In [ ]:
import numpy as np

**Determinando a Matriz Admitância**

In [ ]:
#admitância
def adm(nbarras):
  Y = np.zeros((nbarras,nbarras), dtype=complex)
  print('Se houver Mais de uma conexao entre duas barras iguais somar os valores antes e inserir a soma!!!\n')
  for i in range(nbarras):
    for j in range(nbarras):
      if (Y[j][i]==0):
        if j==i:
          print(f'----------\nPara Y{i+1}{j+1}: ')
          for k in range(nbarras-1):
            rkm = float(input(f'Insira r{k+1}: '))
            xkm = float(input(f'Insira x{k+1}: '))
            zkm = np.complex(rkm,xkm)
            b = float(input(f'Insira b{i+1}{k+2}: '))
            bkm = np.complex(0,b)
            if (zkm!=0):
              Y[i][j] = Y[i][j] + ((1/zkm)+(bkm/2))
        else:
          print(f'---------\nPara Y{i+1}{j+1}: ')
          rkm = float(input(f'Insira r{i+1}{j+1}: '))
          xkm = float(input(f'Insira x{i+1}{j+1}: '))
          zkm = np.complex(rkm,xkm)
          if (zkm!=0):
            ykm = (1/zkm)
            Y[i][j] = -(ykm)
      else:
        Y[i][j] = Y[j][i]      
  return Y    

In [ ]:
#matriz admitância Y = G+jB
Y = adm(4)

Se houver Mais de uma conexao entre duas barras iguais somar os valores antes e inserir a soma!!!

----------
Para Y11: 
Insira r1: 0.005
Insira x1: 0.2
Insira b12: 0.54
Insira r2: 0.0024365
Insira x2: 0.037514
Insira b13: 1.04
Insira r3: 0
Insira x3: 0
Insira b14: 0
---------
Para Y12: 
Insira r12: 0.005
Insira x12: 0.2
---------
Para Y13: 
Insira r13: 0.0024365
Insira x13: 0.037514
---------
Para Y14: 
Insira r14: 0
Insira x14: 0
----------
Para Y22: 
Insira r1: 0.005
Insira x1: 0.2
Insira b22: 0.54
Insira r2: 0.00225
Insira x2: 0.1
Insira b23: 0.88
Insira r3: 0
Insira x3: 0
Insira b24: 0
---------
Para Y23: 
Insira r23: 0.00225
Insira x23: 0.1
---------
Para Y24: 
Insira r24: 0
Insira x24: 0
----------
Para Y33: 
Insira r1: 0.0024365
Insira x1: 0.037514
Insira b32: 1.04
Insira r2: 0.00225
Insira x2: 0.1
Insira b33: 0.88
Insira r3: 0.001
Insira x3: 0.05
Insira b34: 0.44
---------
Para Y34: 
Insira r34: 0.001
Insira x34: 0.05
---------
Para Y41: 
Insira r41: 0
Insira x41: 0
---------


In [ ]:
print(Y,'\n')

[[ 1.84897845-30.75161588j -0.12492192 +4.99687695j
  -1.72405652+26.54473893j  0.         +0.j        ]
 [-0.12492192 +4.99687695j  0.34980808-14.28181701j
  -0.22488615 +9.99494006j  0.         +0.j        ]
 [-1.72405652+26.54473893j -0.22488615 +9.99494006j
   2.34878274-55.35168219j -0.39984006+19.9920032j ]
 [ 0.         +0.j          0.         +0.j
  -0.39984006+19.9920032j   0.39984006-19.7720032j ]] 



In [ ]:
#funcoes
def Hkk(vk,bkk,qk):
  return ((-bkk*(vk**2))-qk)
def Hkm(vk,vm,gkm,bkm,ak,am):
  akm = ak-am
  return ((vk*vm)*(gkm*np.sin(akm)-bkm*np.cos(akm)))

def Nkk(vk,gkk,pk):
  return ((1/vk)*(pk+gkk*vk**2))
def Nkm(vk,gkm,bkm,ak,am):
  akm = ak-am
  return ((vk)*(gkm*np.cos(akm)+bkm*np.sin(akm)))

def Mkk(vk,gkk,pk):
  return ((-gkk*vk**2)+pk)
def Mkm(vk,vm,gkm,bkm,ak,am):
  akm = ak-am
  return ((-vk*vm)*(gkm*np.cos(akm)+bkm*np.sin(akm)))

def Lkk(vk,bkk,qk):
  return ((1/vk)*(qk-bkk*vk**2))
def Lkm(vk,gkm,bkm,ak,am):
  akm = ak-am
  return ((vk)*(gkm*np.sin(akm)-bkm*np.cos(akm)))



**Potências**

In [ ]:
#potências
def potP(v,a,nbarras,Y):
  P = np.zeros(nbarras)
  for i in range(nbarras):
    for j in range(nbarras):
      P[i] = P[i] + ((v[i]*v[j])*(Y[i][j].real*np.cos(a[i]-a[j]) + Y[i][j].imag*np.sin(a[i]-a[j])))
  return P

def potQ(v,a,nbarras,Y):
  Q = np.zeros(nbarras)
  for i in range(nbarras):
    for j in range(nbarras):
      Q[i] = Q[i] + ((v[i]*v[j])*(Y[i][j].real*np.sin(a[i]-a[j]) - Y[i][j].imag*np.cos(a[i]-a[j]))) 
  return Q


**Funções para calculo da Jacobiana**

In [ ]:
#funcoes
def Hkk(v,Q,Y):
  aux = int(input('Insira o indice para Hkk: '))
  k = aux - 1
  print('\n---------------')
  return ((-Y[k][k].imag*v[k]**2)-(Q[k]))
def Hkm(v,a,Y):
  aux1 = int(input('Insira o indice 1 para Hkm: '))
  k = aux1 - 1
  aux2 = int(input('Insira o indice 2 para Hkm: '))
  m = aux2 - 1
  print('\n---------------')
  return ((v[k]*v[m])*(Y[k][m].real*np.sin((a[k]-a[m])) - Y[k][m].imag*np.cos((a[k]-a[m]))))

def Nkk(v,P,Y):
  aux = int(input('Insira o indice para Nkk: '))
  k = aux - 1
  print('\n---------------')
  return ((1/v[k])*(P[k] + Y[k][k].real*v[k]**2))
def Nkm(v,a,Y):
  aux1 = int(input('Insira o indice 1 para Nkm: '))
  k = aux1 - 1
  aux2 = int(input('Insira o indice 2 para Nkm: '))
  m = aux2 - 1
  print('\n---------------')
  return (v[k]*(Y[k][m].real*np.cos((a[k]-a[m])) + Y[k][m].imag*np.sin((a[k]-a[m]))))

def Mkk(v,P,Y):
  aux = int(input('Insira o indice para Mkk: '))
  k = aux - 1
  print('\n---------------')
  return (-(Y[k][k].real*v[k]**2) + P[k])
def Mkm(v,a,Y):
  aux1 = int(input('Insira o indice 1 para Mkm: '))
  k = aux1 - 1
  aux2 = int(input('Insira o indice 2 para Mkm: '))
  m = aux2 - 1
  print('\n---------------')
  return (-(v[k]*v[m])*(Y[k][m].real*np.cos((a[k]-a[m])) + Y[k][m].imag*np.sin((a[k]-a[m]))))

def Lkk(v,Q,Y):
  aux = int(input('Insira o indice para Lkk: '))
  k = aux - 1
  print('\n---------------')
  return ((1/v[k])*(Q[k]-Y[k][k].imag*v[k]**2))
def Lkm(v,a,Y):
  aux1 = int(input('Insira o indice 1 para Lkm: '))
  k = aux1 - 1
  aux2 = int(input('Insira o indice 2 para Lkm: '))
  m = aux2 - 1
  print('\n---------------')
  return (v[k]*(Y[k][m].real*np.sin((a[k]-a[m]))-Y[k][m].imag*np.cos((a[k]-a[m]))))

In [ ]:
def formaJ(npq,npv):
  tam = ((2*npq)+npv)
  form = np.zeros((tam,tam), dtype=str)
  print('Inserir as opções de acordo com as funções H M N L!\n')
  print('Opção KK -> Letra maiúscula  |  Opção KM -> Letra minúscula !\n')
  for i in range(tam):
    for j in range(tam):
      form[i][j] = input(f'Forma J{i}{j}: ')
  return form

In [ ]:
def jacobian(npq,npv,form,v,a,P,Q,Y):
  tam = ((2*npq)+npv)
  J = np.zeros((tam,tam))
  for i in range(tam):
    for j in range(tam):
      print(f'J{i}{j}: ')
      if (form[i][j]=='H'):
        J[i][j] = Hkk(v,Q,Y)
      elif (form[i][j]=='M'):
        J[i][j] = Mkk(v,P,Y)
      elif (form[i][j]=='N'):
        J[i][j] = Nkk(v,P,Y)
      elif (form[i][j]=='L'):
        J[i][j] = Lkk(v,Q,Y)
      elif (form[i][j]=='h'):
        J[i][j] = Hkm(v,a,Y)
      elif (form[i][j]=='m'):
        J[i][j] = Mkm(v,a,Y)
      elif (form[i][j]=='n'):
        J[i][j] = Nkm(v,a,Y)
      elif (form[i][j]=='l'):
        J[i][j] = Lkm(v,a,Y)
  return J  

**Iterações**

In [ ]:
#define-se o numero de barras incialmente
nbarras = 4

#chute (tet2, tet3, tet4, v2, v4)
X = np.array([[0],[0],[0],[1],[1]])
v = np.array([1.03,X[3][0],1.02,X[4][0]])
a = np.array([0,X[0][0],X[1][0],X[2][0]])
#valores esperados (p2,p3,p4,q2,q4)
Pesp = np.array([[-1],[3.6],[-5],[-0.5],[-1]])
#valores calculados
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]],[Q[1]],[Q[3]]])
delPQ = Pesp-pcalc
print('\n','A diferença entre as potencias esperadas e as calculadas é:')
print(delPQ, '\n')

if (abs(np.max(delPQ))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X[0][0],X[1][0],X[2][0],'\n')
  print('para as tensões: \n',X[3][0],X[4][0])
else:
  #Jacobiana
  J = np.array([[Hkk(X[3][0],Y[1][1].imag,pcalc[3][0]),Hkm(X[3][0],1.02,Y[1][2].real,Y[1][2].imag,X[0][0],X[1][0]),Hkm(X[3][0],X[4][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0]),Nkk(X[3][0],Y[1][1].real,pcalc[0][0]),Nkm(X[3][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0])],
      [Hkm(1.02,X[3][0],Y[2][1].real,Y[2][1].imag,X[1][0],X[0][0]),Hkk(1.02,Y[2][2].imag,Q[2]),Hkm(1.02,X[4][0],Y[2][3].real,Y[2][3].imag,X[1][0],X[2][0]),Nkm(1.02,Y[2][1].real,Y[2][1].imag,X[1][0],X[0][0]),Nkm(1.02,Y[2][3].real,Y[2][3].imag,X[1][0],X[2][0])],
      [Hkm(X[4][0],X[3][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Hkm(X[4][0],1.02,Y[3][2].real,Y[3][2].imag,X[2][0],X[1][0]),Hkk(X[4][0],Y[3][3].imag,pcalc[4][0]),Nkm(X[4][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Nkk(X[4][0],Y[3][3].real,pcalc[2][0])],
      [Mkk(X[3][0],Y[1][1].real,pcalc[0][0]),Mkm(X[3][0],1.02,Y[1][2].real,Y[1][2].imag,X[0][0],X[1][0]),Mkm(X[3][0],X[4][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0]),Lkk(X[3][0],Y[1][1].imag,pcalc[3][0]),Lkm(X[3][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0])],
      [Mkm(X[4][0],X[3][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Mkm(X[4][0],1.02,Y[3][2].real,Y[3][2].imag,X[2][0],X[1][0]),Mkk(X[4][0],Y[3][3].real,pcalc[2][0]),Lkm(X[4][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Lkk(X[4][0],Y[3][3].imag,pcalc[4][0])] 
  ])
  print(J,'\n')
  
  # obtendo novo x
  Jinv = np.linalg.inv(J)
  newX = X + (Jinv.dot(delPQ))
  print('O novo Chute:')
  print(newX)


 A diferença entre as potencias esperadas e as calculadas é:
[[-0.99175462]
 [ 3.60484096]
 [-4.9920032 ]
 [ 0.55980511]
 [-0.38015994]] 

[[ 15.34162212 -10.19483886   0.           0.34156269   0.        ]
 [-10.19483886  58.47458485 -20.39184326  -0.22938387  -0.40783687]
 [  0.         -20.39184326  20.39184326   0.           0.39184326]
 [ -0.35805346   0.22938387  -0.          13.2220119    0.        ]
 [ -0.           0.40783687  -0.40783687   0.          19.15216313]] 

O novo Chute:
[[-0.10898453]
 [-0.06536682]
 [-0.30968934]
 [ 1.04052159]
 [ 0.97494781]]


In [ ]:
#chute (tet2, tet3, tet4, v2, v4)
X = newX

v = np.array([1.03,X[3][0],1.02,X[4][0]])
a = np.array([0,X[0][0],X[1][0],X[2][0]])

#valores calculados
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]],[Q[1]],[Q[3]]])
delPQ = Pesp-pcalc
print('\n','A diferença entre as potencias esperadas e as calculadas é:')
print(delPQ, '\n')

if (abs(np.max(delPQ))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X[0][0],X[1][0],X[2][0],'\n')
  print('para as tensões: \n',X[3][0],X[4][0])
else:
  #Jacobiana
  J = np.array([[Hkk(X[3][0],Y[1][1].imag,pcalc[3][0]),Hkm(X[3][0],1.02,Y[1][2].real,Y[1][2].imag,X[0][0],X[1][0]),Hkm(X[3][0],X[4][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0]),Nkk(X[3][0],Y[1][1].real,pcalc[0][0]),Nkm(X[3][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0])],
      [Hkm(1.02,X[3][0],Y[2][1].real,Y[2][1].imag,X[1][0],X[0][0]),Hkk(1.02,Y[2][2].imag,Q[2]),Hkm(1.02,X[4][0],Y[2][3].real,Y[2][3].imag,X[1][0],X[2][0]),Nkm(1.02,Y[2][1].real,Y[2][1].imag,X[1][0],X[0][0]),Nkm(1.02,Y[2][3].real,Y[2][3].imag,X[1][0],X[2][0])],
      [Hkm(X[4][0],X[3][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Hkm(X[4][0],1.02,Y[3][2].real,Y[3][2].imag,X[2][0],X[1][0]),Hkk(X[4][0],Y[3][3].imag,pcalc[4][0]),Nkm(X[4][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Nkk(X[4][0],Y[3][3].real,pcalc[2][0])],
      [Mkk(X[3][0],Y[1][1].real,pcalc[0][0]),Mkm(X[3][0],1.02,Y[1][2].real,Y[1][2].imag,X[0][0],X[1][0]),Mkm(X[3][0],X[4][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0]),Lkk(X[3][0],Y[1][1].imag,pcalc[3][0]),Lkm(X[3][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0])],
      [Mkm(X[4][0],X[3][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Mkm(X[4][0],1.02,Y[3][2].real,Y[3][2].imag,X[2][0],X[1][0]),Mkk(X[4][0],Y[3][3].real,pcalc[2][0]),Lkm(X[4][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Lkk(X[4][0],Y[3][3].imag,pcalc[4][0])] 
  ])
  print(J,'\n')
  
  # obtendo novo x
  Jinv = np.linalg.inv(J)
  newX = X + (Jinv.dot(delPQ))
  print('O novo Chute:')
  print(newX)


 A diferença entre as potencias esperadas e as calculadas é:
[[ 0.0378512 ]
 [ 0.13792205]
 [-0.18505593]
 [-0.06625435]
 [-0.59938603]] 

[[ 15.89645719 -10.58745336   0.          -0.63345075   0.        ]
 [-10.60826801  57.70502762 -19.38672989   0.21536884   4.53704235]
 [ -0.         -19.19436227  19.19436227   0.          -4.54884535]
 [ -1.41658321   0.70099966  -0.          14.44368486   0.        ]
 [ -0.           5.19500134  -5.19500134  -0.          18.86576306]] 

O novo Chute:
[[-0.10734827]
 [-0.0662228 ]
 [-0.32891464]
 [ 1.03613653]
 [ 0.93811841]]


In [ ]:
#chute (tet2, tet3, tet4, v2, v4)
X = newX

v = np.array([1.03,X[3][0],1.02,X[4][0]])
a = np.array([0,X[0][0],X[1][0],X[2][0]])

#valores calculados
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]],[Q[1]],[Q[3]]])
delPQ = Pesp-pcalc
print('\n','A diferença entre as potencias esperadas e as calculadas é:')
print(delPQ, '\n')

if (abs(np.max(delPQ))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X[0][0],X[1][0],X[2][0],'\n')
  print('para as tensões: \n',X[3][0],X[4][0])
else:
  #Jacobiana
  J = np.array([[Hkk(X[3][0],Y[1][1].imag,pcalc[3][0]),Hkm(X[3][0],1.02,Y[1][2].real,Y[1][2].imag,X[0][0],X[1][0]),Hkm(X[3][0],X[4][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0]),Nkk(X[3][0],Y[1][1].real,pcalc[0][0]),Nkm(X[3][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0])],
      [Hkm(1.02,X[3][0],Y[2][1].real,Y[2][1].imag,X[1][0],X[0][0]),Hkk(1.02,Y[2][2].imag,Q[2]),Hkm(1.02,X[4][0],Y[2][3].real,Y[2][3].imag,X[1][0],X[2][0]),Nkm(1.02,Y[2][1].real,Y[2][1].imag,X[1][0],X[0][0]),Nkm(1.02,Y[2][3].real,Y[2][3].imag,X[1][0],X[2][0])],
      [Hkm(X[4][0],X[3][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Hkm(X[4][0],1.02,Y[3][2].real,Y[3][2].imag,X[2][0],X[1][0]),Hkk(X[4][0],Y[3][3].imag,pcalc[4][0]),Nkm(X[4][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Nkk(X[4][0],Y[3][3].real,pcalc[2][0])],
      [Mkk(X[3][0],Y[1][1].real,pcalc[0][0]),Mkm(X[3][0],1.02,Y[1][2].real,Y[1][2].imag,X[0][0],X[1][0]),Mkm(X[3][0],X[4][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0]),Lkk(X[3][0],Y[1][1].imag,pcalc[3][0]),Lkm(X[3][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0])],
      [Mkm(X[4][0],X[3][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Mkm(X[4][0],1.02,Y[3][2].real,Y[3][2].imag,X[2][0],X[1][0]),Mkk(X[4][0],Y[3][3].real,pcalc[2][0]),Lkm(X[4][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Lkk(X[4][0],Y[3][3].imag,pcalc[4][0])] 
  ])
  print(J,'\n')
  
  # obtendo novo x
  Jinv = np.linalg.inv(J)
  newX = X + (Jinv.dot(delPQ))
  print('O novo Chute:')
  print(newX)


 A diferença entre as potencias esperadas e as calculadas é:
[[ 0.00013799]
 [ 0.014078  ]
 [-0.01472402]
 [-0.00032674]
 [-0.02632475]] 

[[ 15.83233076 -10.54454173   0.          -0.60280803   0.        ]
 [-10.56408504  56.84405185 -18.57305368   0.18995937   4.90152802]
 [ -0.         -18.37434617  18.37434617   0.          -4.93902497]
 [ -1.37568456   0.67176795  -0.          14.31566577   0.        ]
 [ -0.           5.33716169  -5.33716169  -0.          17.510578  ]] 

O novo Chute:
[[-0.10735941]
 [-0.06625133]
 [-0.33025618]
 [ 1.03611397]
 [ 0.93621485]]


In [ ]:
#chute (tet2, tet3, tet4, v2, v4)
X = newX

v = np.array([1.03,X[3][0],1.02,X[4][0]])
a = np.array([0,X[0][0],X[1][0],X[2][0]])

#valores calculados
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]],[Q[1]],[Q[3]]])
delPQ = Pesp-pcalc
print('\n','A diferença entre as potencias esperadas e as calculadas é:')
print(delPQ, '\n')

if (abs(np.max(delPQ))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X[0][0],X[1][0],X[2][0],'\n')
  print('para as tensões: \n',X[3][0],X[4][0])
else:
  #Jacobiana
  J = np.array([[Hkk(X[3][0],Y[1][1].imag,pcalc[3][0]),Hkm(X[3][0],1.02,Y[1][2].real,Y[1][2].imag,X[0][0],X[1][0]),Hkm(X[3][0],X[4][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0]),Nkk(X[3][0],Y[1][1].real,pcalc[0][0]),Nkm(X[3][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0])],
      [Hkm(1.02,X[3][0],Y[2][1].real,Y[2][1].imag,X[1][0],X[0][0]),Hkk(1.02,Y[2][2].imag,Q[2]),Hkm(1.02,X[4][0],Y[2][3].real,Y[2][3].imag,X[1][0],X[2][0]),Nkm(1.02,Y[2][1].real,Y[2][1].imag,X[1][0],X[0][0]),Nkm(1.02,Y[2][3].real,Y[2][3].imag,X[1][0],X[2][0])],
      [Hkm(X[4][0],X[3][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Hkm(X[4][0],1.02,Y[3][2].real,Y[3][2].imag,X[2][0],X[1][0]),Hkk(X[4][0],Y[3][3].imag,pcalc[4][0]),Nkm(X[4][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Nkk(X[4][0],Y[3][3].real,pcalc[2][0])],
      [Mkk(X[3][0],Y[1][1].real,pcalc[0][0]),Mkm(X[3][0],1.02,Y[1][2].real,Y[1][2].imag,X[0][0],X[1][0]),Mkm(X[3][0],X[4][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0]),Lkk(X[3][0],Y[1][1].imag,pcalc[3][0]),Lkm(X[3][0],Y[1][3].real,Y[1][3].imag,X[0][0],X[2][0])],
      [Mkm(X[4][0],X[3][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Mkm(X[4][0],1.02,Y[3][2].real,Y[3][2].imag,X[2][0],X[1][0]),Mkk(X[4][0],Y[3][3].real,pcalc[2][0]),Lkm(X[4][0],Y[3][1].real,Y[3][1].imag,X[2][0],X[0][0]),Lkk(X[4][0],Y[3][3].imag,pcalc[4][0])] 
  ])
  print(J,'\n')
  
  # obtendo novo x
  Jinv = np.linalg.inv(J)
  newX = X + (Jinv.dot(delPQ))
  print('O novo Chute:')
  print(newX)


 A diferença entre as potencias esperadas e as calculadas é:
[[ 2.38485387e-09]
 [ 5.34409092e-05]
 [-5.50014033e-05]
 [-9.27124155e-09]
 [-7.32299097e-05]] 

Os resultados são: 

para os ângulos: 
 -0.107359408421364 -0.06625132956255055 -0.33025617761767884 

para as tensões: 
 1.0361139730113678 0.936214849879433


In [ ]:
v = np.array([1.03,X[3][0],1.02,X[4][0]])
a = np.array([0,X[0][0],X[1][0],X[2][0]])
#valores calculados
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)

print('As potências Ativas:')
print(np.round(P,3), '\n')
print('As potências Reativas:')
print(np.round(Q,3))



As potências Ativas:
[ 2.439 -1.     3.6   -5.   ] 

As potências Reativas:
[-0.638 -0.5    0.788 -1.   ]


In [ ]:
#funcao que calcula os fluxos nas linhas
def skm(v1,v2,v3,v4,b12,b13_1,b13_2,b23,b34):
  Y = np.array([[(1.8489-30.7516j),(-0.1249+4.9969j),(-1.724+26.5448j),(0)],
                [(-0.1249+4.9969j),(0.3498-14.2818j),(-0.2249+9.9949j),(0)],
                [(-1.724+26.5448j),(-0.2249+9.9949j),(2.3487-55.3517j),(-0.3998+19.992j)],
                [(0),(0),(-0.3998+19.992j),(0.3998-19.772j)]])
  S12 = np.conj(v1)*(-(Y[0][1])*(v1-v2)+(b12)*(v1))
  S131 = np.conj(v1)*(-(Y[0][2])*(v1-v3)+(b13_1)*(v1))
  S132 = np.conj(v1)*(-(Y[0][2])*(v1-v2)+(b13_2)*(v1))
  S23 = np.conj(v2)*(-(Y[1][2])*(v2-v3)+(b23)*(v2))
  S34 = np.conj(v3)*(-(Y[2][3])*(v3-v4)+(b34)*(v3))
  Sr = np.array([[S12],[S131],[S132],[S23],[S34]])
  return Sr



In [ ]:
Sramos = skm(1.03,(1.0301-0.111j),(1.0178-0.0675j),(0.8856-0.3036j),0.54j,0.82j,0.22j,0.88j,0.44j)
Sline = np.conj(Sramos)
print(Sline)

Stot = np.sum(Sline)
print('\n',Stot)

[[ 0.57128271-0.5876805j ]
 [ 1.867191  -0.65623714j]
 [ 3.03468941-0.43323703j]
 [-0.43028347-0.75994715j]
 [ 5.02995063+1.81393052j]]

 (10.07283028941-0.6231712984420006j)
