<a href="https://colab.research.google.com/github/luisfgb/ET720/blob/main/fluxodecarga_desacoplado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ET720 - Exercicio 2**

In [ ]:
import numpy as np

**Matriz Admitância**

In [ ]:
#INSERIR NUMERO DE BARRAS
nbarras = 4

In [ ]:
#admitância
def adm(nbarras):
  Y = np.zeros((nbarras,nbarras), dtype=complex)
  print('Se houver Mais de uma conexao entre duas barras iguais somar os valores antes e inserir a soma!!!\n')
  for i in range(nbarras):
    for j in range(nbarras):
      if (Y[j][i]==0):
        if j==i:
          print(f'----------\nPara Y{i+1}{j+1}: ')
          for k in range(nbarras-1):
            rkm = float(input(f'Insira r{k+1}: '))
            xkm = float(input(f'Insira x{k+1}: '))
            zkm = np.complex(rkm,xkm)
            b = float(input(f'Insira b{i+1}{k+2}: '))
            bkm = np.complex(0,b)
            if (zkm!=0):
              Y[i][j] = Y[i][j] + ((1/zkm)+(bkm/2))
        else:
          print(f'---------\nPara Y{i+1}{j+1}: ')
          rkm = float(input(f'Insira r{i+1}{j+1}: '))
          xkm = float(input(f'Insira x{i+1}{j+1}: '))
          zkm = np.complex(rkm,xkm)
          if (zkm!=0):
            ykm = (1/zkm)
            Y[i][j] = -(ykm)
      else:
        Y[i][j] = Y[j][i]      
  return Y    

In [ ]:
Y = adm(nbarras)

Se houver Mais de uma conexao entre duas barras iguais somar os valores antes e inserir a soma!!!

----------
Para Y11: 
Insira r1: 0.005
Insira x1: 0.2
Insira b12: 0.54
Insira r2: 0.0024365
Insira x2: 0.037514
Insira b13: 1.04
Insira r3: 0
Insira x3: 0
Insira b14: 0
---------
Para Y12: 
Insira r12: 0.005
Insira x12: 0.2
---------
Para Y13: 
Insira r13: 0.0024365
Insira x13: 0.037514
---------
Para Y14: 
Insira r14: 0
Insira x14: 0
----------
Para Y22: 
Insira r1: 0.005
Insira x1: 0.2
Insira b22: 0.54
Insira r2: 0.00225
Insira x2: 0.1
Insira b23: 0.88
Insira r3: 0
Insira x3: 0
Insira b24: 0
---------
Para Y23: 
Insira r23: 0.00225
Insira x23: 0.1
---------
Para Y24: 
Insira r24: 0
Insira x24: 0
----------
Para Y33: 
Insira r1: 0.0024365
Insira x1: 0.037514
Insira b32: 1.04
Insira r2: 0.00225
Insira x2: 0.1
Insira b33: 0.88
Insira r3: 0.001
Insira x3: 0.05
Insira b34: 0.44
---------
Para Y34: 
Insira r34: 0.001
Insira x34: 0.05
---------
Para Y41: 
Insira r41: 0
Insira x41: 0
---------


In [ ]:
print(Y)

[[ 1.84897845-30.75161588j -0.12492192 +4.99687695j
  -1.72405652+26.54473893j  0.         +0.j        ]
 [-0.12492192 +4.99687695j  0.34980808-14.28181701j
  -0.22488615 +9.99494006j  0.         +0.j        ]
 [-1.72405652+26.54473893j -0.22488615 +9.99494006j
   2.34878274-55.35168219j -0.39984006+19.9920032j ]
 [ 0.         +0.j          0.         +0.j
  -0.39984006+19.9920032j   0.39984006-19.7720032j ]]


**Fórmula para cálculo das potências**

In [ ]:
#potências
def potP(v,a,nbarras,Y):
  P = np.zeros(nbarras)
  for i in range(nbarras):
    for j in range(nbarras):
      P[i] = P[i] + ((v[i]*v[j])*(Y[i][j].real*np.cos(a[i]-a[j]) + Y[i][j].imag*np.sin(a[i]-a[j])))
  return P

def potQ(v,a,nbarras,Y):
  Q = np.zeros(nbarras)
  for i in range(nbarras):
    for j in range(nbarras):
      Q[i] = Q[i] + ((v[i]*v[j])*(Y[i][j].real*np.sin(a[i]-a[j]) - Y[i][j].imag*np.cos(a[i]-a[j]))) 
  return Q

**Fórmulas para cálculo das Matrizes**

In [ ]:
#definindo a função de H'
def Hline(Y,Q,v,a):
  tam = int(input('Insira o tamanho da matriz H:'))
  Hl = np.zeros((tam,tam), dtype=float)
  for i in range(tam):
    for j in range(tam):
      if (i==j):
        index = int(input(f'Índice para a potência do elemento H{i}{j}:'))
        aux = (index-1)
        Hl[i][j] = -(Q[aux]/v[aux]) - (Y[aux][aux].imag*v[aux])
      else:
        index1 = int(input(f'Índice 1 para a potência do elemento H{i}{j}:'))
        index2 = int(input(f'Índice 2 para a potência do elemento H{i}{j}:'))
        aux1 = (index1-1)
        aux2 = (index2-1)
        Hl[i][j] = (v[aux2]*(Y[aux1][aux2].real*np.sin((a[aux1]-a[aux2]))-Y[aux1][aux2].imag*np.cos((a[aux1]-a[aux2]))))
  return Hl

#definindo a função de L'
def Lline(Y,Q,v,a):
  tam = int(input('Insira o tamanho da matriz L:'))
  Ll = np.zeros((tam,tam), dtype=float)
  for i in range(tam):
    for j in range(tam):
      if (i==j):
        index = int(input(f'Índice para a potência do elemento L{i}{j}:'))
        aux = (index-1)
        Ll[i][j] = (Q[aux]/v[aux]**2)-(Y[aux][aux].imag)
      else:
        index1 = int(input(f'Índice 1 para a potência do elemento H{i}{j}:'))
        index2 = int(input(f'Índice 2 para a potência do elemento H{i}{j}:'))
        aux1 = (index1-1)
        aux2 = (index2-1)
        Ll[i][j] = (Y[aux1][aux2].real*np.sin((a[aux1]-a[aux2]))-Y[aux1][aux2].imag*np.cos((a[aux1]-a[aux2])))
  return Ll   

**Iterações**

In [ ]:

#chutes
#teta2, teta3, teta4
X1 = np.array([[0],[0],[0]])
#v2 , v4
X2 = np.array([[1],[1]])

v = [1.03,X2[0][0],1.02,X2[1][0]]
a = [0,X1[0][0],X1[1][0],X1[2][0]]

#valores esperados (p2,p3,p4,q2,q4)
Pesp = np.array([[-1],[3.6],[-5]])
Qesp = np.array([[-0.5],[-1]])

#calculando as potencias ativas
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]]])
delP = Pesp-pcalc
#pn está especifico!!!!!!
pn = np.array([[v[1]],[v[2]],[v[3]]])
delPn = delP/pn
print('A diferença entre as potencias ativas esperadas e as calculadas é:\n')
print(delP,'\n')

if (np.max(abs(delP))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X1,'\n')
else:
  #meia iteração ativa
  H = Hline(Y,Q,v,a)
  print('\nH:\n',H,'\n')
  # obtendo novos angulos
  Hinv = np.linalg.inv(H)
  newX1 = X1 + (Hinv.dot(delPn))
  print('o novo chute dos angulos:','\n',newX1,'\n')
  X1 = newX1
a = [0,X1[0][0],X1[1][0],X1[2][0]] 

#meia iteração reativa
Q = potQ(v,a,nbarras,Y)
qcalc = np.array([[Q[1]],[Q[3]]])
delQ = Qesp - qcalc
#qn está especifico!!!!!!
qn = np.array([[v[1]],[v[3]]])
delQn = delQ/qn
print('A diferença entre as potencias reativas esperadas e as calculadas é:\n')
print(delQ,'\n')

if (np.max(abs(delQ))<0.0001):
  print('Os resultados são: \n')
  print('para as tensões: \n',X2,'\n')
else:
#obtendo a matriz L
  L = Lline(Y,Q,v,a)
  print('\nL:\n',L,'\n')
  Linv = np.linalg.inv(L)
  print('\n','A diferença entre as potencias reativas esperadas e as calculadas é:')
  print(delQ)
  newX2 = X2 + (Linv.dot(delQn))
  print('\n', 'o novo chute das tensoes','\n',newX2)
  X2 = newX2
  


A diferença entre as potencias ativas esperadas e as calculadas é:

[[-0.99175462]
 [ 3.60484096]
 [-4.9920032 ]] 

Insira o tamanho da matriz H:3
Índice para a potência do elemento H00:2
Índice 1 para a potência do elemento H01:2
Índice 2 para a potência do elemento H01:3
Índice 1 para a potência do elemento H02:2
Índice 2 para a potência do elemento H02:4
Índice 1 para a potência do elemento H10:3
Índice 2 para a potência do elemento H10:2
Índice para a potência do elemento H11:3
Índice 1 para a potência do elemento H12:3
Índice 2 para a potência do elemento H12:4
Índice 1 para a potência do elemento H20:4
Índice 2 para a potência do elemento H20:2
Índice 1 para a potência do elemento H21:4
Índice 2 para a potência do elemento H21:3
Índice para a potência do elemento H22:4

H:
 [[ 15.34162212 -10.19483886   0.        ]
 [ -9.99494006  57.32802436 -19.9920032 ]
 [  0.         -20.39184326  20.39184326]] 

o novo chute dos angulos: 
 [[-0.10807593]
 [-0.06535714]
 [-0.31016106]] 

A di

In [ ]:
v = [1.03,X2[0][0],1.02,X2[1][0]]
a = [0,X1[0][0],X1[1][0],X1[2][0]]

#calculando as potencias ativas
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]]])
delP = Pesp-pcalc
#pn está especifico!!!!!!
pn = np.array([[v[1]],[v[2]],[v[3]]])
delPn = delP/pn
print('A diferença entre as potencias ativas esperadas e as calculadas é:\n')
print(delP,'\n')

if (np.max(abs(delP))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X1,'\n')
else:
  #meia iteração ativa
  H = Hline(Y,Q,v,a)
  print('\nH:\n',H,'\n')
  # obtendo novos angulos
  Hinv = np.linalg.inv(H)
  newX1 = X1 + (Hinv.dot(delPn))
  print('o novo chute dos angulos:','\n',newX1,'\n')
  X1 = newX1

a = [0,X1[0][0],X1[1][0],X1[2][0]]

#meia iteração reativa
Q = potQ(v,a,nbarras,Y)
qcalc = np.array([[Q[1]],[Q[3]]])
delQ = Qesp - qcalc
#qn está especifico!!!!!!
qn = np.array([[v[1]],[v[3]]])
delQn = delQ/qn
print('A diferença entre as potencias reativas esperadas e as calculadas é:\n')
print(delQ,'\n')

if (np.max(abs(delQ))<0.0001):
  print('Os resultados são: \n')
  print('para as tensões: \n',X2,'\n')
else:
#obtendo a matriz L
  L = Lline(Y,Q,v,a)
  print('\nL:\n',L,'\n')
  Linv = np.linalg.inv(L)
  print('\n','A diferença entre as potencias reativas esperadas e as calculadas é:')
  print(delQ)
  newX2 = X2 + (Linv.dot(delQn))
  print('\n', 'o novo chute das tensoes','\n',newX2)
  X2 = newX2

A diferença entre as potencias ativas esperadas e as calculadas é:

[[ 0.0215691 ]
 [ 0.27346066]
 [-0.31147468]] 

Insira o tamanho da matriz H:3
Índice para a potência do elemento H00:2
Índice 1 para a potência do elemento H01:2
Índice 2 para a potência do elemento H01:3
Índice 1 para a potência do elemento H02:2
Índice 2 para a potência do elemento H02:4
Índice 1 para a potência do elemento H10:3
Índice 2 para a potência do elemento H10:2
Índice para a potência do elemento H11:3
Índice 1 para a potência do elemento H12:3
Índice 2 para a potência do elemento H12:4
Índice 1 para a potência do elemento H20:4
Índice 2 para a potência do elemento H20:2
Índice 1 para a potência do elemento H21:4
Índice 2 para a potência do elemento H21:3
Índice para a potência do elemento H22:4

H:
 [[ 15.27861721 -10.175742     0.        ]
 [-10.36920973  55.96183658 -18.4258966 ]
 [ -0.         -19.6850119   19.6850119 ]] 

o novo chute dos angulos: 
 [[-0.10728533]
 [-0.06621331]
 [-0.3277564 ]] 

A di

In [ ]:
v = [1.03,X2[0][0],1.02,X2[1][0]]
a = [0,X1[0][0],X1[1][0],X1[2][0]]

#calculando as potencias ativas
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]]])
delP = Pesp-pcalc
#pn está especifico!!!!!!
pn = np.array([[v[1]],[v[2]],[v[3]]])
delPn = delP/pn
print('A diferença entre as potencias ativas esperadas e as calculadas é:\n')
print(delP,'\n')

if (np.max(abs(delP))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X1,'\n')
else:
  #meia iteração ativa
  H = Hline(Y,Q,v,a)
  print('\nH:\n',H,'\n')
  # obtendo novos angulos
  Hinv = np.linalg.inv(H)
  newX1 = X1 + (Hinv.dot(delPn))
  print('o novo chute dos angulos:','\n',newX1,'\n')
  X1 = newX1

a = [0,X1[0][0],X1[1][0],X1[2][0]]

#meia iteração reativa
Q = potQ(v,a,nbarras,Y)
qcalc = np.array([[Q[1]],[Q[3]]])
delQ = Qesp - qcalc
#qn está especifico!!!!!!
qn = np.array([[v[1]],[v[3]]])
delQn = delQ/qn
print('A diferença entre as potencias reativas esperadas e as calculadas é:\n')
print(delQ,'\n')

if (np.max(abs(delQ))<0.0001):
  print('Os resultados são: \n')
  print('para as tensões: \n',X2,'\n')
else:
#obtendo a matriz L
  L = Lline(Y,Q,v,a)
  print('\nL:\n',L,'\n')
  Linv = np.linalg.inv(L)
  print('\n','A diferença entre as potencias reativas esperadas e as calculadas é:')
  print(delQ)
  newX2 = X2 + (Linv.dot(delQn))
  print('\n', 'o novo chute das tensoes','\n',newX2)
  X2 = newX2

A diferença entre as potencias ativas esperadas e as calculadas é:

[[-0.00076783]
 [ 0.04098692]
 [-0.04114167]] 

Insira o tamanho da matriz H:3
Índice para a potência do elemento H00:2
Índice 1 para a potência do elemento H01:2
Índice 2 para a potência do elemento H01:3
Índice 1 para a potência do elemento H02:2
Índice 2 para a potência do elemento H02:4
Índice 1 para a potência do elemento H10:3
Índice 2 para a potência do elemento H10:2
Índice para a potência do elemento H11:3
Índice 1 para a potência do elemento H12:3
Índice 2 para a potência do elemento H12:4
Índice 1 para a potência do elemento H20:4
Índice 2 para a potência do elemento H20:2
Índice 1 para a potência do elemento H21:4
Índice 2 para a potência do elemento H21:3
Índice para a potência do elemento H22:4

H:
 [[ 15.28023624 -10.17682257   0.        ]
 [-10.35680046  55.71356349 -18.19308872]
 [ -0.         -19.59290515  19.59290515]] 

o novo chute dos angulos: 
 [[-0.10735749]
 [-0.06624885]
 [-0.33003285]] 

A di

In [ ]:
v = [1.03,X2[0][0],1.02,X2[1][0]]
a = [0,X1[0][0],X1[1][0],X1[2][0]]

#calculando as potencias ativas
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]]])
delP = Pesp-pcalc
#pn está especifico!!!!!!
pn = np.array([[v[1]],[v[2]],[v[3]]])
delPn = delP/pn
print('A diferença entre as potencias ativas esperadas e as calculadas é:\n')
print(delP,'\n')

if (np.max(abs(delP))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X1,'\n')
else:
  #meia iteração ativa
  H = Hline(Y,Q,v,a)
  print('\nH:\n',H,'\n')
  # obtendo novos angulos
  Hinv = np.linalg.inv(H)
  newX1 = X1 + (Hinv.dot(delPn))
  print('o novo chute dos angulos:','\n',newX1,'\n')
  X1 = newX1

a = [0,X1[0][0],X1[1][0],X1[2][0]]

#meia iteração reativa
Q = potQ(v,a,nbarras,Y)
qcalc = np.array([[Q[1]],[Q[3]]])
delQ = Qesp - qcalc
#qn está especifico!!!!!!
qn = np.array([[v[1]],[v[3]]])
delQn = delQ/qn
print('A diferença entre as potencias reativas esperadas e as calculadas é:\n')
print(delQ,'\n')

if (np.max(abs(delQ))<0.0001):
  print('Os resultados são: \n')
  print('para as tensões: \n',X2,'\n')
else:
#obtendo a matriz L
  L = Lline(Y,Q,v,a)
  print('\nL:\n',L,'\n')
  Linv = np.linalg.inv(L)
  print('\n','A diferença entre as potencias reativas esperadas e as calculadas é:')
  print(delQ)
  newX2 = X2 + (Linv.dot(delQn))
  print('\n', 'o novo chute das tensoes','\n',newX2)
  X2 = newX2

A diferença entre as potencias ativas esperadas e as calculadas é:

[[-4.15277550e-06]
 [ 3.75513442e-03]
 [-3.78489713e-03]] 

Insira o tamanho da matriz H:3
Índice para a potência do elemento H00:2
Índice 1 para a potência do elemento H01:2
Índice 2 para a potência do elemento H01:3
Índice 1 para a potência do elemento H02:2
Índice 2 para a potência do elemento H02:4
Índice 1 para a potência do elemento H10:3
Índice 2 para a potência do elemento H10:2
Índice para a potência do elemento H11:3
Índice 1 para a potência do elemento H12:3
Índice 2 para a potência do elemento H12:4
Índice 1 para a potência do elemento H20:4
Índice 2 para a potência do elemento H20:2
Índice 1 para a potência do elemento H21:4
Índice 2 para a potência do elemento H21:3
Índice para a potência do elemento H22:4

H:
 [[ 15.28016349 -10.17679884   0.        ]
 [-10.35672457  55.6885205  -18.16824889]
 [ -0.         -19.58015734  19.58015734]] 

o novo chute dos angulos: 
 [[-0.10735932]
 [-0.06625121]
 [-0.33024

In [ ]:
v = [1.03,X2[0][0],1.02,X2[1][0]]
a = [0,X1[0][0],X1[1][0],X1[2][0]]

#calculando as potencias ativas
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]]])
delP = Pesp-pcalc
#pn está especifico!!!!!!
pn = np.array([[v[1]],[v[2]],[v[3]]])
delPn = delP/pn
print('A diferença entre as potencias ativas esperadas e as calculadas é:\n')
print(delP,'\n')

if (np.max(abs(delP))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X1,'\n')
else:
  #meia iteração ativa
  H = Hline(Y,Q,v,a)
  print('\nH:\n',H,'\n')
  # obtendo novos angulos
  Hinv = np.linalg.inv(H)
  newX1 = X1 + (Hinv.dot(delPn))
  print('o novo chute dos angulos:','\n',newX1,'\n')
  X1 = newX1

a = [0,X1[0][0],X1[1][0],X1[2][0]]

#meia iteração reativa
Q = potQ(v,a,nbarras,Y)
qcalc = np.array([[Q[1]],[Q[3]]])
delQ = Qesp - qcalc
#qn está especifico!!!!!!
qn = np.array([[v[1]],[v[3]]])
delQn = delQ/qn
print('A diferença entre as potencias reativas esperadas e as calculadas é:\n')
print(delQ,'\n')

if (np.max(abs(delQ))<0.0001):
  print('Os resultados são: \n')
  print('para as tensões: \n',X2,'\n')
else:
#obtendo a matriz L
  L = Lline(Y,Q,v,a)
  print('\nL:\n',L,'\n')
  Linv = np.linalg.inv(L)
  print('\n','A diferença entre as potencias reativas esperadas e as calculadas é:')
  print(delQ)
  newX2 = X2 + (Linv.dot(delQn))
  print('\n', 'o novo chute das tensoes','\n',newX2)
  X2 = newX2

A diferença entre as potencias ativas esperadas e as calculadas é:

[[-3.94964725e-08]
 [ 3.15226477e-04]
 [-3.17705912e-04]] 

Insira o tamanho da matriz H:3
Índice para a potência do elemento H00:2
Índice 1 para a potência do elemento H01:2
Índice 2 para a potência do elemento H01:3
Índice 1 para a potência do elemento H02:2
Índice 2 para a potência do elemento H02:4
Índice 1 para a potência do elemento H10:3
Índice 2 para a potência do elemento H10:2
Índice para a potência do elemento H11:3
Índice 1 para a potência do elemento H12:3
Índice 2 para a potência do elemento H12:4
Índice 1 para a potência do elemento H20:4
Índice 2 para a potência do elemento H20:2
Índice 1 para a potência do elemento H21:4
Índice 2 para a potência do elemento H21:3
Índice para a potência do elemento H22:4

H:
 [[ 15.28016258 -10.17679918   0.        ]
 [-10.35672402  55.68633717 -18.16607456]
 [ -0.         -19.57897792  19.57897792]] 

o novo chute dos angulos: 
 [[-0.10735945]
 [-0.0662514 ]
 [-0.33025

In [ ]:
v = [1.03,X2[0][0],1.02,X2[1][0]]
a = [0,X1[0][0],X1[1][0],X1[2][0]]

#calculando as potencias ativas
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[1]],[P[2]],[P[3]]])
delP = Pesp-pcalc
#pn está especifico!!!!!!
pn = np.array([[v[1]],[v[2]],[v[3]]])
delPn = delP/pn
print('A diferença entre as potencias ativas esperadas e as calculadas é:\n')
print(delP,'\n')

if (np.max(abs(delP))<=0.0001):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X1,'\n')
else:
  #meia iteração ativa
  H = Hline(Y,Q,v,a)
  print('\nH:\n',H,'\n')
  # obtendo novos angulos
  Hinv = np.linalg.inv(H)
  newX1 = X1 + (Hinv.dot(delPn))
  print('o novo chute dos angulos:','\n',newX1,'\n')
  X1 = newX1

a = [0,X1[0][0],X1[1][0],X1[2][0]]

#meia iteração reativa
Q = potQ(v,a,nbarras,Y)
qcalc = np.array([[Q[1]],[Q[3]]])
delQ = Qesp - qcalc
#qn está especifico!!!!!!
qn = np.array([[v[1]],[v[3]]])
delQn = delQ/qn
print('A diferença entre as potencias reativas esperadas e as calculadas é:\n')
print(delQ,'\n')

if (np.max(abs(delQ))<0.0001):
  print('Os resultados são: \n')
  print('para as tensões: \n',X2,'\n')
else:
#obtendo a matriz L
  L = Lline(Y,Q,v,a)
  print('\nL:\n',L,'\n')
  Linv = np.linalg.inv(L)
  print('\n','A diferença entre as potencias reativas esperadas e as calculadas é:')
  print(delQ)
  newX2 = X2 + (Linv.dot(delQn))
  print('\n', 'o novo chute das tensoes','\n',newX2)
  X2 = newX2

A diferença entre as potencias ativas esperadas e as calculadas é:

[[-7.10542736e-15]
 [ 6.92846669e-10]
 [-8.03642486e-10]] 

Os resultados são: 

para os ângulos: 
 [[-0.10735945]
 [-0.0662514 ]
 [-0.33025919]] 

A diferença entre as potencias reativas esperadas e as calculadas é:

[[-5.00909501e-08]
 [-9.28146193e-05]] 

Os resultados são: 

para as tensões: 
 [[1.03611397]
 [0.93621507]] 



In [ ]:
v = [1.03,X2[0][0],1.02,X2[1][0]]
a = [0,X1[0][0],X1[1][0],X1[2][0]]

In [ ]:
#calculando as magnitudes e angulos
#rad*180/pi
degrees = np.zeros(3)
for i in range(3):
  degrees[i] = X1[i][0]*(180/np.pi)
print('As magnitudes e angulos das tensões:')
print('V1 : 1.03 / 0 º')
print('V2 :',X2[0][0] ,'/',degrees[0],'º')
print('V3 : 1.02 /',degrees[1],'º')
print('V4 :',X2[1][0] ,'/',degrees[2],'º')  

As magnitudes e angulos das tensões:
V1 : 1.03 / 0 º
V2 : 1.0361139747154036 / -6.151243590640018 º
V3 : 1.02 / -3.795925489034553 º
V4 : 0.9362150706212321 / -18.9224575469188 º


 **Cálculo das potências**

In [ ]:
#fasores
V = np.array([1.03,X2[0][0],1.02,X2[1][0]])
rad = np.array([0,X1[0][0],X1[1][0],X1[2][0]])
E = []
for i in range(4):
  E.append(V[i]*(np.exp(np.complex(0,rad[i])))) 
print(E)

[(1.03+0j), (1.030148555894341-0.11102306692465172j), (1.0177623023217146-0.06752700180522608j), (0.8856204391920525-0.3036035180026654j)]


In [ ]:
#funcao que calcula os fluxos nas linhas

def skm(v1,v2,v3,v4,b12,b13_1,b13_2,b23,b34,Y):
  S12 = np.conj(v1)*(-(Y[0][1])*(v1-v2)+(b12/2)*(v1))
  S21 = np.conj(v2)*(-(Y[1][0])*(v2-v1)+(b12/2)*(v2))
  S131 = np.conj(v1)*((1/(0.009+0.1j))*(v1-v3)+(b13_1/2)*(v1))
  S311 = np.conj(v3)*((1/(0.009+0.1j))*(v3-v1)+(b13_1/2)*(v3))
  S132 = np.conj(v1)*((1/(0.003+0.06j))*(v1-v3)+(b13_2/2)*(v1))
  S312 = np.conj(v3)*((1/(0.003+0.06j))*(v3-v1)+(b13_2/2)*(v3))
  S23 = np.conj(v2)*(-(Y[1][2])*(v2-v3)+(b23/2)*(v2))
  S32 = np.conj(v3)*(-(Y[2][1])*(v3-v2)+(b23/2)*(v3))
  S34 = np.conj(v3)*(-(Y[2][3])*(v3-v4)+(b34)/2*(v3))
  S43 = np.conj(v4)*(-(Y[3][2])*(v4-v3)+(b34/2)*(v4))
  Sr = np.array([[S12+S21],[S131+S311],[S132+S312],[S23+S32],[S34+S43]])
  return Sr

In [ ]:
#valores calculados
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
print('As potências Ativas:')
print(np.round(P,4), '\n')
print('As potências Reativas:')
print(np.round(Q,4))


As potências Ativas:
[ 2.4394 -1.      3.6    -5.    ] 

As potências Reativas:
[-0.6385 -0.5     0.7879 -0.9999]


In [ ]:
Sramos = skm(E[0],E[1],E[2],E[3],0.54j,0.82j,0.22j,0.88j,0.44j,Y)
Sline = np.conj(Sramos)
print('As perdas por ramos são: ')
print(Sline)
Sptot = np.sum(Sline)
print('\n As perdas totais são: ',Sptot)
S = []
for k in range(4):
  S.append(np.complex(P[k],Q[k]))
print('\n As injeções de potência em cada barra: ',np.round(S,3))

print('\n O delta S é:',np.round(np.sum(S)-Sptot,3))


As perdas por ramos são: 
[[0.00153981-0.51470446j]
 [0.00420463-0.81481484j]
 [0.00391493-0.15284446j]
 [0.00045997-0.90968723j]
 [0.02926573+1.04156885j]]

 As perdas totais são:  (0.039385063356501104-1.3504821511359806j)

 As injeções de potência em cada barra:  [ 2.439-0.638j -1.   -0.5j    3.6  +0.788j -5.   -1.j   ]

 O delta S é: -0j
