<a href="https://colab.research.google.com/github/luisfgb/ET720/blob/main/fluxo_rapido.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Fluxo de carga desacoplado rápido**

In [ ]:
import numpy as np

In [ ]:
#INSERIR O NUMERO DE BARRAS
nbarras = 3

**Matriz Admitância**

In [ ]:
#admitância
def adm(nbarras):
  Y = np.zeros((nbarras,nbarras), dtype=complex)
  for i in range(nbarras):
    for j in range(nbarras):
      if (Y[j][i]==0):
        if j==i:
          print(f'----------\nPara Y{i+1}{j+1}: ')
          nconn = int(input(f'Qual o numero de conexões da barra {i+1}: '))
          for k in range(nconn):
            rkm = float(input(f'Insira r{k+1}: '))
            xkm = float(input(f'Insira x{k+1}: '))
            zkm = np.complex(rkm,xkm)
            b = float(input(f'Insira b{i+1}{k+2}: '))
            bkm = np.complex(0,b)
            if (zkm!=0):
              Y[i][j] = Y[i][j] + ((1/zkm)+(bkm/2))
        else:
          print(f'---------\nPara Y{i+1}{j+1}: ')
          ncon = int(input(f'Número de conexões {i+1}{j+1}: '))
          for k in range(ncon):
            rkm = float(input(f'Insira r{i+1}{j+1}: '))
            xkm = float(input(f'Insira x{i+1}{j+1}: '))
            zkm = np.complex(rkm,xkm)
            if (zkm!=0):
              ykm = (1/zkm)
              Y[i][j] = Y[i][j] -(ykm)
      else:
        Y[i][j] = Y[j][i]      
  return Y 

In [ ]:
#matriz admitância 
Y = adm(nbarras)
print('Y:\n',Y)

----------
Para Y11: 
Qual o numero de conexões da barra 1: 2
Insira r1: 0.01
Insira x1: 0.05
Insira b12: 0.2
Insira r2: 0.01
Insira x2: 0.04
Insira b13: 0.2
---------
Para Y12: 
Número de conexões 12: 1
Insira r12: 0.01
Insira x12: 0.05
---------
Para Y13: 
Número de conexões 13: 1
Insira r13: 0.01
Insira x13: 0.04
----------
Para Y22: 
Qual o numero de conexões da barra 2: 3
Insira r1: 0.01
Insira x1: 0.05
Insira b22: 0.2
Insira r2: 0.04
Insira x2: 0.29
Insira b23: 0.3
Insira r3: 0.04
Insira x3: 0.2
Insira b24: 0.1
---------
Para Y23: 
Número de conexões 23: 2
Insira r23: 0.04
Insira x23: 0.29
Insira r23: 0.04
Insira x23: 0.2
----------
Para Y33: 
Qual o numero de conexões da barra 3: 3
Insira r1: 0.01
Insira x1: 0.04
Insira b32: 0.2
Insira r2: 0.04
Insira x2: 0.29
Insira b33: 0.3
Insira r3: 0.04
Insira x3: 0.2
Insira b34: 0.1
Y:
 [[ 9.72850679-42.560181j   -3.84615385+19.23076923j
  -5.88235294+23.52941176j]
 [-3.84615385+19.23076923j  5.27443677-27.12235885j
  -1.42828292 +8.191589

**Fórmula para cálculo da potência**

In [ ]:
#potências
def potP(v,a,nbarras,Y):
  P = np.zeros(nbarras)
  for i in range(nbarras):
    for j in range(nbarras):
      P[i] = P[i] + ((v[i]*v[j])*(Y[i][j].real*np.cos(a[i]-a[j]) + Y[i][j].imag*np.sin(a[i]-a[j])))
  return P

def potQ(v,a,nbarras,Y):
  Q = np.zeros(nbarras)
  for i in range(nbarras):
    for j in range(nbarras):
      Q[i] = Q[i] + ((v[i]*v[j])*(Y[i][j].real*np.sin(a[i]-a[j]) - Y[i][j].imag*np.cos(a[i]-a[j]))) 
  return Q

**Cálculo das Matrizes B' e B''**

In [ ]:
def bkkline(index1,index2,nconn):
  i=0
  x = np.zeros(nconn)
  while i<=(nconn-1):
    print('Insira xkm para b',index1,index2)
    x[i] = (float(input('Xkm:')))
    i = i+1
  bkk=0
  for k in range(nconn):
    bkk = bkk + (1/x[k])
  return bkk 

def bkmline(xkm):
  if xkm == 0:
    return 0
  else:
    return -(1/xkm)

In [ ]:
#matriz B'
def Bline():
  tam = int(input('Defina o tamanho da matriz Bl: '))
  Bl=np.zeros((tam,tam))
  for i in range(tam):
    for k in range(tam):
      if (Bl[k][i]==0):
        if i==k:
          Bl[i][k] = bkkline(i,k,int(input(f'\nNumero de conexoes Bkk {i+1}: ',)))
        else:
          Bl[i][k] = bkmline(float(input(f'Insira X{i}{k}: ')))
      else:
        Bl[i][k] = Bl[k][i]
  return Bl

#matriz B''
def Blline(Y):
  tam = int(input('Defina o tamanho da matriz Bll: '))
  Bll = np.zeros((tam,tam))
  for i in range(tam):
    for j in range(tam):
      if (Bll[j][i]==0):
        if (i==j):
          index = int(input(f'\nIndice do elemento Bll{i}{j}: '))
          Bll[i][j] = -(Y[index-1][index-1].imag)
        else:
          index1 = int(input(f'\nIndice 1 do elemento Bll{i}{j}: '))
          index2 = int(input(f'Indice 2 do elemento Bll{i}{j}: '))
          Bll[i][j] = -(Y[index1-1][index2-1].imag)
      else:
        Bll[i][j] = Bll[j][i]
  return Bll




In [ ]:
#determinando as matrizes
Bl = Bline()
Bll = Blline(Y)
print('\nBl:\n',Bl,'\n')
print('\nBll:\n',Bll,'\n')

Defina o tamanho da matriz Bl: 2

Numero de conexoes Bkk 1: 2
Insira xkm para b 0 0
Xkm:0.05
Insira xkm para b 0 0
Xkm:0.04
Insira X01: 0.05

Numero de conexoes Bkk 2: 3
Insira xkm para b 1 1
Xkm:0.05
Insira xkm para b 1 1
Xkm:0.29
Insira xkm para b 1 1
Xkm:0.2
Defina o tamanho da matriz Bll: 1

Indice do elemento Bll00: 1

Bl:
 [[ 45.         -20.        ]
 [-20.          28.44827586]] 


Bll:
 [[42.560181]] 



**Iterações**

In [ ]:

#chutes
#teta1, teta2
X1 = np.array([[0],[0]])
#v1
X2 = np.array([[1]])

v = [X2[0][0],1.015,1.010]
a = [X1[0][0],X1[1][0],0.1745]

#valores esperados (p1,p2,q1)
Pesp = np.array([[-2.9],[3]])
Qesp = np.array([[-1]])

#calculando as potencias ativas
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[0]],[P[1]]])
delP = Pesp-pcalc
#pn está especifico!!!!!! --> v1,v2
pn = np.array([[v[0]],[v[1]]])
delPn = delP/pn
print('A diferença entre as potencias ativas esperadas e as calculadas é:\n')
print(delP,'\n')

if (np.max(abs(delP))<=0.01):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X1,'\n')
else:
  #meia iteração ativa
  #obtendo novos angulos
  Blinv = np.linalg.inv(Bl)
  newX1 = X1 + (Blinv.dot(delPn))
  print('o novo chute dos angulos:','\n',newX1,'\n')
  X1 = newX1
a = [X1[0][0],X1[1][0],0.1745] 

#obtendo Q para novos angulos
Q = potQ(v,a,nbarras,Y)
qcalc = np.array([Q[0]])
delQ = Qesp - qcalc

#qn está especifico!!!!!! -->V1
qn = np.array([v[0]])
delQn = delQ/qn
print('A diferença entre as potencias reativas esperadas e as calculadas é:\n')
print(delQ,'\n')

if (np.max(abs(delQ))<0.01):
  print('Os resultados são: \n')
  print('para as tensões: \n',X2,'\n')
else:
  #meia iteração reativa
  Bllinv = np.linalg.inv(Bll)
  newX2 = X2 + (Bllinv.dot(delQn))
  print('\n', 'o novo chute das tensoes','\n',newX2)
  X2 = newX2
  


A diferença entre as potencias ativas esperadas e as calculadas é:

[[1.25221728]
 [4.36991464]] 

o novo chute dos angulos: 
 [[0.13830258]
 [0.24856994]] 

A diferença entre as potencias reativas esperadas e as calculadas é:

[[-1.05496076]] 


 o novo chute das tensoes 
 [[0.97521249]]


In [ ]:
v = [X2[0][0],1.015,1.010]
a = [X1[0][0],X1[1][0],0.1745]

#calculando as potencias ativas
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[0]],[P[1]]])
delP = Pesp-pcalc
#pn está especifico!!!!!! --> v1,v2
pn = np.array([[v[0]],[v[1]]])
delPn = delP/pn
print('A diferença entre as potencias ativas esperadas e as calculadas é:\n')
print(delP,'\n')

if (np.max(abs(delP))<=0.01):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X1,'\n')
else:
  #meia iteração ativa
  #obtendo novos angulos
  Blinv = np.linalg.inv(Bl)
  newX1 = X1 + (Blinv.dot(delPn))
  print('o novo chute dos angulos:','\n',newX1,'\n')
  X1 = newX1
a = [X1[0][0],X1[1][0],0.1745]

#obtendo Q para novos angulos
Q = potQ(v,a,nbarras,Y)
qcalc = np.array([Q[0]])
delQ = Qesp - qcalc

#qn está especifico!!!!!! -->V1
qn = np.array([v[0]])
delQn = delQ/qn
print('A diferença entre as potencias reativas esperadas e as calculadas é:\n')
print(delQ,'\n')

if (np.max(abs(delQ))<0.01):
  print('Os resultados são: \n')
  print('para as tensões: \n',X2,'\n')
else:
  #meia iteração reativa
  Bllinv = np.linalg.inv(Bll)
  newX2 = X2 + (Bllinv.dot(delQn))
  print('\n', 'o novo chute das tensoes','\n',newX2)
  X2 = newX2

A diferença entre as potencias ativas esperadas e as calculadas é:

[[0.35532614]
 [0.09411713]] 

o novo chute dos angulos: 
 [[0.15218608]
 [0.26158993]] 

A diferença entre as potencias reativas esperadas e as calculadas é:

[[0.07009842]] 


 o novo chute das tensoes 
 [[0.9769014]]


In [ ]:
v = [X2[0][0],1.015,1.010]
a = [X1[0][0],X1[1][0],0.1745]

#calculando as potencias ativas
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
pcalc = np.array([[P[0]],[P[1]]])
delP = Pesp-pcalc
#pn está especifico!!!!!! --> v1,v2
pn = np.array([[v[0]],[v[1]]])
delPn = delP/pn
print('A diferença entre as potencias ativas esperadas e as calculadas é:\n')
print(delP,'\n')

if (np.max(abs(delP))<=0.01):
  print('Os resultados são: \n')
  print('para os ângulos: \n',X1,'\n')
else:
  #meia iteração ativa
  #obtendo novos angulos
  Blinv = np.linalg.inv(Bl)
  newX1 = X1 + (Blinv.dot(delPn))
  print('o novo chute dos angulos:','\n',newX1,'\n')
  X1 = newX1
a = [X1[0][0],X1[1][0],0.1745]

#obtendo Q para novos angulos
Q = potQ(v,a,nbarras,Y)
qcalc = np.array([Q[0]])
delQ = Qesp - qcalc

#qn está especifico!!!!!! -->V1
qn = np.array([v[0]])
delQn = delQ/qn
print('A diferença entre as potencias reativas esperadas e as calculadas é:\n')
print(delQ,'\n')

if (np.max(abs(delQ))<0.01):
  print('Os resultados são: \n')
  print('para as tensões: \n',X2,'\n')
else:
  #meia iteração reativa
  Bllinv = np.linalg.inv(Bll)
  newX2 = X2 + (Bllinv.dot(delQn))
  print('\n', 'o novo chute das tensoes','\n',newX2)
  X2 = newX2

A diferença entre as potencias ativas esperadas e as calculadas é:

[[0.00908867]
 [0.00325438]] 

Os resultados são: 

para os ângulos: 
 [[0.15218608]
 [0.26158993]] 

A diferença entre as potencias reativas esperadas e as calculadas é:

[[0.00173183]] 

Os resultados são: 

para as tensões: 
 [[0.9769014]] 



In [ ]:
#calculando as magnitudes e angulos
#rad*180/pi
degrees = np.zeros(2)
for i in range(2):
  degrees[i] = X1[i][0]*(180/np.pi)
print('As magnitudes e angulos das tensões:')
print(f'V1 : {X2[0][0]} / {degrees[0]} º')
print(f'V2 :1.015 / {degrees[1]} º')
print('V3 : 1.010 / 10 º')
  

As magnitudes e angulos das tensões:
V1 : 0.9769013998928194 / 8.719619917474457 º
V2 :1.015 / 14.9879987617116 º
V3 : 1.010 / 10 º


### **Cálculo das Injeções de Potência e Perdas**


In [ ]:
v = [X2[0][0],1.015,1.010]
a = [X1[0][0],X1[1][0],0.1745]

#valores calculados
P = potP(v,a,nbarras,Y)
Q = potQ(v,a,nbarras,Y)
print('As potências Ativas:')
print(np.round(P,4), '\n')
print('As potências Reativas:')
print(np.round(Q,4))

As potências Ativas:
[-2.9091  2.9967 -0.016 ] 

As potências Reativas:
[-1.0017  0.0782  0.4746]


In [ ]:
#cálculo das tensoes fasoriais
V = np.array([X2[0][0],1.015,1.010])
rad = np.array([X1[0][0],X1[1][0],0.1745])
E = []
for i in range(3):
  E.append(V[i]*(np.exp(np.complex(0,rad[i])))) 
print(E)

[(0.9656104050522887+0.14809757178058422j), (0.9804697178912769+0.2624959662512925j), (0.9946616045780811+0.17535191010695328j)]


In [ ]:
#funcao que calcula os fluxos nas linhas

def skm(v1,v2,v3,b12,b13,b23,b32,Y):
  S12 = np.conj(v1)*(-(Y[0][1])*(v1-v2)+(b12/2)*(v1))
  S21 = np.conj(v2)*(-(Y[1][0])*(v2-v1)+(b12/2)*(v2))
  S13 = np.conj(v1)*(-(Y[0][2])*(v1-v3)+(b13/2)*(v1))
  S31 = np.conj(v3)*(-(Y[2][0])*(v3-v1)+(b13/2)*(v3))
  S231 = np.conj(v1)*((1/(0.04+0.29j))*(v1-v3)+(b23/2)*(v1))
  S321 = np.conj(v3)*((1/(0.04+0.29j))*(v3-v1)+(b23/2)*(v3))
  S232 = np.conj(v2)*(((1/(0.04+0.2j)))*(v2-v3)+(b32/2)*(v2))
  S322 = np.conj(v3)*(((1/(0.04+0.2j)))*(v3-v2)+(b32/2)*(v3))
  Sr = np.array([[S12+S21],[S13+S31],[S231+S321],[S232+S322]])
  print(S12)
  return Sr

In [ ]:
#calculos das perdas
Sramos = skm(E[0],E[1],E[2],0.2j,0.2j,0.3j,0.1j,Y)
Sline = np.conj(Sramos)
print('As perdas por ramos são: ')
print(Sline)
Sptot = np.sum(Sline)
print('\n As perdas totais são: ',Sptot)
S = []
for k in range(3):
  S.append(np.complex(P[k],Q[k]))
print('\n As injeções de potência em cada barra: ',np.round(S,3))

print('\n O delta S é:',np.round(np.sum(S)-Sptot,3))

(-2.20234111880005+0.28077404127051314j)
As perdas por ramos são: 
[[0.05118381+0.05746294j]
 [0.00933395-0.16010784j]
 [0.00074062-0.29079598j]
 [0.00749567-0.0650379j ]]

 As perdas totais são:  (0.06875404873540958-0.4584787876220074j)

 As injeções de potência em cada barra:  [-2.909-1.002j  2.997+0.078j -0.016+0.475j]

 O delta S é: (0.003+0.01j)
